Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'회원탈퇴를 하고 싶어요.','회원탈퇴를 하고 싶어요.',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'카카오톡으로는 어떻게 문의할 수 있나요?','카카오톡으로는 어떻게 문의할 수 있나요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'회원 탈퇴 후 동일한 연락처로 재가입이 가능한가요?','회원 탈퇴 후 동일한 연락처로 재가입이 가능한가요?',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'교환/반품 기준이 어떻게 되나요?','교환/반품 기준이 어떻게 되나요?',219,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'아이디와 비밀번호가 생각나지 않아요. 어떻게 찾을 수 있나요?','아이디와 비밀번호가 생각나지 않아요. 어떻게 찾을 수 있나요?',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'묶음 배송이 가능한가요?','묶음 배송이 가능한가요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'이벤트 문자는 오는데, 배송완료문자만 오지 않습니다.','이벤트 문자는 오는데, 배송완료문자만 오지 않습니다.',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'주문이 안 됩니다.','주문이 안 됩니다.',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'회원 정보를 변경하려면 어떻게 해야 하나요?','회원 정보를 변경하려면 어떻게 해야 하나요?',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'쿠폰은 어떻게 적용하나요?','쿠폰은 어떻게 적용하나요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 공동현관문에 비밀번호가 있어야 출입이 가능한데 배송을 어떻게 받을 수 있나요?','(샛별배송) 공동현관문에 비밀번호가 있어야 출입이 가능한데 배송을 어떻게 받을 수 있나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'팝업이 안 보여요.','팝업이 안 보여요.',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'할인 된 금액은 어디서 확인 할 수 있나요?','할인 된 금액은 어디서 확인 할 수 있나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'상품 주문은 어떻게 하나요?','상품 주문은 어떻게 하나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'전화로도 주문할 수 있나요?','전화로도 주문할 수 있나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'비회원도 상품 주문이 가능한가요?','비회원도 상품 주문이 가능한가요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'비회원 주문확인 및 배송 조회는 어떻게 할 수 있나요?','비회원 주문확인 및 배송 조회는 어떻게 할 수 있나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'배송 가능 지역인지 어떻게 확인하나요?','배송 가능 지역인지 어떻게 확인하나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'현금영수증/세금계산서 발급은 어떻게 하나요?','현금영수증/세금계산서 발급은 어떻게 하나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'샛별배송 또는 택배배송을 선택 할 수 있나요?','샛별배송 또는 택배배송을 선택 할 수 있나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'마켓컬리는 어떤 회사인가요? 믿고 주문할 수 있는 곳 인가요?','마켓컬리는 어떤 회사인가요? 믿고 주문할 수 있는 곳 인가요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'현금영수증 발행을 취소하고 싶어요.','현금영수증 발행을 취소하고 싶어요.',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'배송지역 검색을 했더니 배송불가라고 떠요.','배송지역 검색을 했더니 배송불가라고 떠요.',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'유기농과 친환경, 무농약의 차이는 뭔가요?','유기농과 친환경, 무농약의 차이는 뭔가요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'마켓컬리에서 어떤 결제방법을 제공하나요?','마켓컬리에서 어떤 결제방법을 제공하나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'대량주문은 어떻게 신청하나요?','대량주문은 어떻게 신청하나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'관공서, 학교, 회사, 시장, 공업단지로도 샛별배송이 가능한가요?','관공서, 학교, 회사, 시장, 공업단지로도 샛별배송이 가능한가요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'비회원 주문내역에 대한 실적 합산이 가능한가요?','비회원 주문내역에 대한 실적 합산이 가능한가요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'상품후기는 어떻게 남길 수 있나요?','상품후기는 어떻게 남길 수 있나요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'후기 적립금은 얼마인가요?','후기 적립금은 얼마인가요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'회원가입은 무료인가요?','회원가입은 무료인가요?',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 배송완료 알림톡 또는 문자는 언제 오나요?','(샛별배송) 배송완료 알림톡 또는 문자는 언제 오나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'주문 취소는 어떻게 하나요?','주문 취소는 어떻게 하나요?',219,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'30만원 이상 결제시 공인인증서 인증이 꼭 필요 한가요?','30만원 이상 결제시 공인인증서 인증이 꼭 필요 한가요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'상품을 교환/반품 하고 싶어요.','상품을 교환/반품 하고 싶어요.',219,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 배송시간 및 날짜를 정할 수 있나요?','(샛별배송) 배송시간 및 날짜를 정할 수 있나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'적립금, 쿠폰은 어디서 볼 수 있나요?','적립금, 쿠폰은 어디서 볼 수 있나요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'상품 문의는 어떻게 하나요?','상품 문의는 어떻게 하나요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'무통장입금은 없나요?','무통장입금은 없나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'마켓 컬리 회원가입을 하면 어떤 혜택이 있나요?','마켓 컬리 회원가입을 하면 어떤 혜택이 있나요?',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 카드키가 필요한데 출입은 어떻게 하나요?','(샛별배송) 카드키가 필요한데 출입은 어떻게 하나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'문자를 받고 싶지 않은데 수신거부는 어떻게 하나요?','문자를 받고 싶지 않은데 수신거부는 어떻게 하나요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'적립금은 어떻게 쌓을 수 있나요?','적립금은 어떻게 쌓을 수 있나요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'결제내역을 문자나 메일로 받아 볼 수 있나요?','결제내역을 문자나 메일로 받아 볼 수 있나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'교환시 별도 배송비가 부과되나요?','교환시 별도 배송비가 부과되나요?',219,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'외국인이나 해외에 거주하는 사람도 회원가입 할 수 있나요?','외국인이나 해외에 거주하는 사람도 회원가입 할 수 있나요?',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 새벽에 공동현관출입이 어려운 경우 어떻게 해야하나요?','(샛별배송) 새벽에 공동현관출입이 어려운 경우 어떻게 해야하나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'적립금은 어떻게 적용하나요?','적립금은 어떻게 적용하나요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 현관, 경비실 앞에 배송이 되었어요.','(샛별배송) 현관, 경비실 앞에 배송이 되었어요.',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'주문취소/반품 후 사용했던 적립금/쿠폰은 재사용 가능한가요?','주문취소/반품 후 사용했던 적립금/쿠폰은 재사용 가능한가요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(회원) 적립금 적용은 어떻게 하나요?','(회원) 적립금 적용은 어떻게 하나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(회원) 쿠폰 적용은 어떻게 하나요?','(회원) 쿠폰 적용은 어떻게 하나요?',218,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'적립금은 유효기간이 있나요?','적립금은 유효기간이 있나요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'주문 후 주문정보(배송지, 메모, 출입방법 등)변경하려고 하는데 어떻게 해야하나요?','주문 후 주문정보(배송지, 메모, 출입방법 등)변경하려고 하는데 어떻게 해야하나요?',220,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'내가 주문한 내역은 어떻게 확인하나요?','내가 주문한 내역은 어떻게 확인하나요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'상품을 반품했는데 아직 카드취소가 되지 않았어요. 어떻게 된 건가요?','상품을 반품했는데 아직 카드취소가 되지 않았어요. 어떻게 된 건가요?',219,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'주문하지 않았는데, 주문완료 메시지 또는 배송완료 메시지를 받았습니다.','주문하지 않았는데, 주문완료 메시지 또는 배송완료 메시지를 받았습니다.',217,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'장바구니 상품은 언제까지 보관이 되나요?','장바구니 상품은 언제까지 보관이 되나요?',222,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'적립금 유효기간은 어떻게 확인하나요?','적립금 유효기간은 어떻게 확인하나요?',221,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'교환 또는 반품신청 시에 사진을 첨부해야 하나요?','교환 또는 반품신청 시에 사진을 첨부해야 하나요?',219,'y',to_date('21/03/12','RR/MM/DD'));
Insert into QUESTION (QNO,TITLE,content,CTNO,TYPE,WRITEDATE) values (s_question.nextval,'(샛별배송) 어제 주문했는데 오늘 아침에 배송이 안 됐어요. 왜 그런가요?','(샛별배송) 어제 주문했는데 오늘 아침에 배송이 안 됐어요. 왜 그런가요?',218,'y',to_date('21/03/12','RR/MM/DD'));
commit;